plugins:
  - jekyll-paginate

paginate: 5
paginate_path: "/page:num/"

collections:
    authors:
      output: true
  
defaults:
    - scope:
        path: ""
        type: "authors"
      values:
        layout: "author"
    - scope:
        path: ""
        type: "posts"
      values:
        layout: "post"
    - scope:
        path: ""
      values:
        layout: "default"

# Site settings
title: "Diário de Leitura"
baseurl: "/mybooks"
url: "https://greicefelipe.github.io/"
permalink: /:categories/:title:output_ext
